<a href="https://colab.research.google.com/github/cawllol/NLP_Sentiment-Classification-using-SpaCy-for-IMDB-and-Amazon-Review-Dataset/blob/master/Amazon_and_IMDB_Review_Sentiment_Classification_using_SpaCy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Amazon and IMDB Review Sentiment Classification using SpaCy**

**NLP:**
Natural Language Processing (NLP) is the field of Artificial Intelligence concerned with the processing and understanding of human language. Since its inception during the 1950s, machine understanding of language has played a pivotal role in translation, topic modeling, document indexing, information retrieval, and extraction.

**Application of NLP:** Text Classification,Spam Filters,Voice text messaging,Sentiment analysis,Spell or grammar check,Chat bot,Search Suggestion,Search Autocorrect, Automatic Review Analysis system, Machine translation and so much more.


**Data Cleaning Options:**
Case Normalization, Removing Stop Words, Removing Punctuations or Special Symbols, Lemmatization or Stemming, Parts of Speech Tagging, Entity Detection, Bag of Words, TF-IDF.

**Bag of Words:** The Simplest Word Embedding Technique
This is one of the simplest methods of embedding words into numerical vectors. It is not often used in practice due to its oversimplification of language, but often the first embedding technique to be taught in the classroom setting.

doc1 = "I am high"

doc2 = "Yes I am high"

doc3 = "I am kidding"

**Let's Get Started**

In [50]:
import spacy
from spacy import displacy

In [51]:
nlp = spacy.load('en_core_web_sm')

In [52]:
text = "Apple, This is first sentence. and Google this is another one. here 3rd one is"

In [53]:
doc = nlp(text)

In [54]:
doc

Apple, This is first sentence. and Google this is another one. here 3rd one is

In [55]:
for token in doc:
    print(token)

Apple
,
This
is
first
sentence
.
and
Google
this
is
another
one
.
here
3rd
one
is


In [56]:
sent = nlp.create_pipe('sentencizer')

In [57]:
nlp.add_pipe(sent, before='parser')

In [58]:
doc = nlp(text)

In [59]:
for sent in doc.sents:
    print(sent)

Apple, This is first sentence.
and Google this is another one.
here 3rd one is


In [60]:
from spacy.lang.en.stop_words import STOP_WORDS

In [61]:
stopwords = list(STOP_WORDS)

In [62]:
print(stopwords)

['afterwards', 'anyone', 'hereafter', 'nowhere', '‘s', 'me', 'part', 'upon', 'over', 'there', 'when', 'it', 'nothing', '‘ve', 'due', 'latterly', 'your', 'sometime', 'n’t', 'per', 'ten', 'be', 'twelve', 'out', 'are', 'regarding', 'that', 'back', 'being', 'some', 'within', 'been', 'moreover', 'seeming', 'empty', 'seems', 'yourself', 'keep', 'alone', "n't", "'m", 'top', 'therein', 'such', 'amount', 'may', 'him', 'wherever', 'serious', 'which', 'you', 'next', 'thru', 'every', 'give', 'less', 'they', '‘re', 'until', 'eleven', 'i', 'rather', 'anything', 'their', 'used', 'whole', 'unless', 'besides', 'move', 'this', 'whereas', '‘d', 'have', 'has', 'than', 'if', 'only', 'sometimes', 'yours', '‘ll', 'noone', 'should', 'does', 'whoever', 'without', 'hence', 'the', 'itself', "'ve", 'become', 'something', 'ourselves', 'or', 'themselves', 'under', "'re", 'own', 'four', 'against', 'almost', 'beforehand', 'cannot', 'will', '’re', 'hereupon', 'nine', 'seem', 'through', 'anywhere', 'beyond', 'meanwhile

In [63]:
len(stopwords)

326

In [64]:
for token in doc:
    if token.is_stop == False:
        print(token)

Apple
,
sentence
.
Google
.
3rd


**Lemmatization**

In [65]:
doc = nlp('run runs running runner')

In [66]:
for lem in doc:
    print(lem.text, lem.lemma_)

run run
runs run
running run
runner runner


**POS**

In [67]:
doc = nlp('All is well at your end!')

In [68]:
for token in doc:
    print(token.text, token.pos_)

All DET
is AUX
well ADV
at ADP
your DET
end NOUN
! PUNCT


In [115]:
displacy.render(doc, style = 'dep',jupyter=True)

**Entity Detection**

In [70]:
doc = nlp("New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn’s Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthodox Jews, to receive inoculations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.")

In [71]:
doc

New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn’s Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthodox Jews, to receive inoculations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.

In [72]:
displacy.render(doc, style = 'ent')

'<div class="entities" style="line-height: 2.5; direction: ltr">\n<mark class="entity" style="background: #feca74; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    New York City\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">GPE</span>\n</mark>\n on \n<mark class="entity" style="background: #bfe1d9; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    Tuesday\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">DATE</span>\n</mark>\n declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases. \n<mark class="entity" style="background: #e4e7d2; padding: 0.45em

**Text Classification**

In [73]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [74]:
data_yelp = pd.read_csv('/content/yelp_labelled.txt', sep='\t', header = None)

In [75]:
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [76]:
columns_name = ['Review', 'Sentiment']
data_yelp.columns = columns_name

In [77]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [78]:
data_yelp.shape

(1000, 2)

In [79]:
data_amazon = pd.read_csv('/content/amazon_cells_labelled.txt', sep = '\t', header = None)
data_amazon.columns = columns_name

In [80]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [81]:
data_amazon.shape

(1000, 2)

In [82]:
data_imdb = pd.read_csv('/content/imdb_labelled.txt', sep = '\t', header = None)

In [83]:
data_imdb.columns = columns_name

In [84]:
data_imdb.shape

(748, 2)

In [85]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [86]:
data = data_yelp.append([data_amazon, data_imdb], ignore_index=True)

In [87]:
data.shape

(2748, 2)

In [88]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [89]:
data['Sentiment'].value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [90]:
data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

**Tokenization**

In [91]:
import string

In [92]:
punct = string.punctuation

In [93]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [94]:
def text_data_cleaning(sentence):
    doc = nlp(sentence)
    
    tokens = []
    for token in doc:
        if token.lemma_ != "-PRON-":
            temp = token.lemma_.lower().strip()
        else:
            temp = token.lower_
        tokens.append(temp)
    
    cleaned_tokens = []
    for token in tokens:
        if token not in stopwords and token not in punct:
            cleaned_tokens.append(token)
    return cleaned_tokens

In [95]:
text_data_cleaning("    Hello how are you. Like this video")

['hello', 'like', 'video']

**Vectorization Feature Engineering (TF-IDF)**

In [96]:
from sklearn.svm import LinearSVC

In [97]:
tfidf = TfidfVectorizer(tokenizer = text_data_cleaning)
classifier = LinearSVC()

In [98]:
X = data['Review']
y = data['Sentiment']

In [99]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [100]:
X_train.shape, X_test.shape

((2198,), (550,))

In [101]:
clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])

In [102]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=<function text_data_cleaning at 0x7f0a8d08d8c8>,
                                 use_idf=True, vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept

In [103]:
y_pred = clf.predict(X_test)

In [104]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.82      0.80       285
           1       0.79      0.74      0.77       265

    accuracy                           0.78       550
   macro avg       0.78      0.78      0.78       550
weighted avg       0.78      0.78      0.78       550



In [105]:
confusion_matrix(y_test, y_pred)

array([[233,  52],
       [ 68, 197]])

In [106]:
clf.predict(['Wow, this is amzing lesson'])

array([1])

In [107]:
clf.predict(['Wow, this sucks'])

array([0])

In [108]:
clf.predict(['Worth of watching it. Please like it'])

array([1])

In [109]:
clf.predict(['Loved it. amazing'])

array([1])